# Dockerfile
# Инструкции для сборки Docker-образа

# 1. Базовый образ Python
# Используем официальный образ Python 3.10 slim-buster для меньшего размера
FROM python:3.10-slim-buster

# 2. Установка системных зависимостей
# OpenCV требует некоторых системных библиотек
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

# 3. Установка рабочей директории внутри контейнера
WORKDIR /app

# 4. Копирование файла зависимостей и установка зависимостей Python
# Копируем сначала requirements.txt, чтобы Docker мог кэшировать этот слой,
# если зависимости не менялись.
COPY requirements.txt .
# Обновляем pip и устанавливаем зависимости
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# 5. Копирование кода приложения в рабочую директорию
COPY . .

# 6. Указание порта, который будет слушать контейнер
EXPOSE 8000

# 7. Команда для запуска приложения при старте контейнера
# Запускаем Uvicorn сервер, указывая точку входа (main:app)
# host 0.0.0.0 делает его доступным извне контейнера
# port 8000 - порт, который мы открыли (EXPOSE)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
